baseURL = "https://suy0n9.com"
languageCode = "ja-jp"
title = "suy0n9.com"
googleAnalytics = "UA-103680121-3"
theme = "etch"

[params]
    copyright = "suy0n9 All Right Reserved."
    dark = "auto"
    highlight = true
    website = "https://suy0n9.com"

[author]
    name = "suy0n9"

[taxonomies]
    category = "categories"
    tag = "tags"
