baseURL = "https://suy0n9.com"
languageCode = "ja-jp"
hasCJKLanguage = true
title = "suy0n9.com"
googleAnalytics = "G-TQYFB9F1KZ"
theme = "kiss"
copyright = "&copy; suy0n9 All Right Reserved."
rssLimit = 10
Paginate = 10

[author]
    name = "suy0n9"

[taxonomies]
    category = "categories"
    tag = "tags"

[params.rss]
    includeContent = true

[params.assets]
    customCSS = ["css/custom.css"]

[params.info]
    enableSocial = true # Adds OpenGraph and Twitter cards
    related = true # Includes related articles at the bottom of the article
    codeCopy = true # Add copy button above code blocks

[permalinks]
    posts = "/posts/:year/:month/:day/:filename/"

[params.social]
    github = "suy0n9"
    twitter = "suy0n9"
    rss = "index.xml"

[params.social.config]
    platforms = ["github", "twitter", "rss"]

[params.sections_right]
"https://suy0n9.me" = "About"
