baseURL = "https://suy0n9.com"
languageCode = "ja-jp"
title = "suy0n9.com"
googleAnalytics = "UA-103680121-3"
theme = "kiss"
copyright = "&copy; suy0n9 All Right Reserved."
Paginate = 10

[author]
    name = "suy0n9"

[taxonomies]
    category = "categories"
    tag = "tags"

[params.assets]
    customCSS = ["css/custom.css"]

[permalinks]
    posts = "/posts/:year/:month/:day/:filename/"

[params.social]
    github = "suy0n9"
    twitter = "suy0n9"

[params.social.config]
    platforms = ["github","twitter"]
