baseURL = "https://suy0n9.com"
languageCode = "ja-jp"
hasCJKLanguage = true
title = "suy0n9.com"
googleAnalytics = "G-TQYFB9F1KZ"
theme = "kiss"
copyright = "&copy; suy0n9 All Right Reserved."
rssLimit = 10
Paginate = 10

[author]
    name = "suy0n9"

[taxonomies]
    category = "categories"
    tag = "tags"

[params.rss]
    includeContent = true

[params.assets]
    customCSS = ["css/custom.css"]

[params.info]
    enableSocial = true # Adds OpenGraph and Twitter cards

[permalinks]
    posts = "/posts/:year/:month/:day/:filename/"

[params.social]
    github = "suy0n9"
    twitter = "suy0n9"

[params.social.config]
    platforms = ["github","twitter"]
